version: '2'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "x"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "x"
      DB_MYSQL_PASSWORD: "x"
      DB_MYSQL_NAME: "x"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'x'
      MYSQL_DATABASE: 'x'
      MYSQL_USER: 'x'
      MYSQL_PASSWORD: 'x'
    volumes:
      - ./data/mysql:/var/lib/mysql
